t = (10, 20, 30, 20, 40) 
print("Tuple:", t) 
print("Count of 20:", t.count(20)) 
print("Index of 30:", t.index(30)) 
print("Length:", len(t)) 
print("Maximum:", max(t)) 
print("Minimum:", min(t)) 